export const SET_EXPENSES = "SET_EXPENSES";
export const CLEAR_EXPENSES = "CLEAR_EXPENSES";
export const ADD_EXPENSE = "ADD_EXPENSE";

export const ATTEMPTING_LOGIN = "ATTEMPTING_LOGIN";
export const ATTEMPTING_LOGOUT = "ATTEMPTING_LOGOUT";
export const AWAITING_AUTH_RESPONSE = "AWAITING_AUTH_RESPONSE";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";
export const SIGNED_IN = "SIGNED_IN";
export const SIGNED_OUT = "SIGNED_OUT";
export const ANONYMOUS = "ANONYMOUS";

export const START_UPLOAD = "START_UPLOAD";
export const SET_UPLOAD_PROGRESS = "SET_UPLOAD_PROGRESS";
export const COMPLETE_UPLOAD = "COMPLETE_UPLOAD";
export const NO_ACTIVITY = "NO_ACTIVITY";
export const UPLOADING = "UPLOADING";
